* 田正林,余岳峰,朱小磊,王宇,张忠孝.基于图像处理的燃气火焰稳定性检测试验研究[J].动力工程学报,2019,39(10):811-817.
** 问题
1. 燃气锅炉的炉膛燃烧情况对锅炉运行安全有重要影响。燃烧不稳定会导致锅炉热效率降低，污染物排放量增大，甚至炉膛熄火。
2. 传统火焰探测器一般只能探测到燃烧强度和燃烧频率，可探测到的火焰信息很少且视角很小，当负荷变化时误判概率会增加。图像火焰检测具有传统火焰探测器不具备的优点，其具有宽视角探测范围，能适应不同工况下燃烧火焰变动引起的信号变化，且图像包含更多的火焰信息，可提取多个火焰特征量进行燃烧状态的综合判断。
** 方法
文章搭建了燃气火焰图像检测试验系统，选取精确高效的图像处理算法处理火焰图像，并根据定义的６个火焰特征量以支持向量机（SVM）的方式对火焰稳定性进行判别。
** 讨论
1. 将通过单CCD相机采集的图像数据经过3×3邻域内线性插值方法转变为分辨率为493×656的RGB矩阵图像，并对图像进行灰度化处理后，采用中值滤波法为图像去噪声，采用最大类间方差法进行图像分割。
2. 燃气火焰稳定燃烧时会呈现有规律的闪烁，导致火焰的形状和亮度呈现周期性变化；燃烧稳定性遭到破坏时，燃气火焰的形状、亮度和位置等信息会偏离原来变化的均值。故文章提取６个火焰特征量，即火焰面积、高度、边缘长度、平均灰度、形心和亮度中心描述火焰相关特征。经过实验分析，火焰参数与实际现象一致，说明图像处理与特征提取均较为准确。
3. 以大量稳定火焰、脱火火焰和回火火焰的特征值为样本数据，以样本火焰提取的特征量为输入量训练分类器svmStruct，以区分出稳定燃烧、预混脱火、预混回火和扩散脱火。在火焰稳定性实时检测试验中，各类型火焰检测正确率均达到99%，实现了火焰燃烧稳定性检测试验研究的目的。
** 结论
1. 将图像灰度化可有效降低图像滤波和分割时的计算量，使程序处理速度满足实时要求。
2. 基于辐射出的可见光能量，以火焰的形状和亮度等信息判断燃烧稳定性是一种直观可靠的方法。
3. 火焰各特征值并不独立，且各特征值随工况参数的变化并非线性函数或简单函数，将原始参数空间映射到更高维空间，使样本在高维空间中线性可分。
4. 提取的火焰面积、高度、边缘长度、形心、亮度中心、平均灰度６个特征量均随火焰稳定性变化而呈现出相应的变化规律。
5. 文章在整体写法上具有借鉴性。
* 王煜伟,田宏伟,秦永新,韩哲哲,许传龙.基于火焰图像和卷积稀疏自编码的燃烧工况监测[J].动力工程学报,2020,40(09):713-719.
** 问题
1. 不稳定燃烧不仅会降低能源利用效率，增加污染物排放量，还可能造成热分布不均匀、炉壁热应力增大等问题。因此，有必要对锅炉燃烧状态进行有效监测，以确保锅炉安全稳定运行。
2. 无监督学习网络在很大程度上降低了标签数据的需求量，自编码（AE）就是其中典型的无监督学习网络，但是AE在训练过程中往往会出现梯度消失或梯度爆炸等现象，且存在简单复制输入层信息的可能，不能真正获取图像的关键信息。因此，仍需开发更智能的图像特征提取方法。
** 方法
一种基于卷积稀疏自编码（CSAE）的燃煤电站锅炉燃烧状态识别方法。
首先，建立的CSAE以无监督方式提取图像特征，然后通过Soft-max分类器实现特征分类，从而识别单张火焰图像的燃烧工况，最后在300MW电站锅炉上获取火焰图像，对所建立模型进行了训练与性能测试。
** 讨论
1. 火焰图像经过预处理后（将所有火焰图像尺寸压缩至64*64，并进行归一化处理），划分为训练集（80%）和测试集（20%）。用于训练CSAE网络的数据集包含3240张火焰图像，定义为数据集A；用于训练Soft-max分类器的数据集包含360张火焰图像，定义为数据集B；用于测试CASE-Soft-max模型的数据集包含900张火焰图像，定义为数据集C。
2. 利用数据集A对CSAE网络进行训练。随着迭代次数的增加，重构误差进一步减小，并在120次迭代训练后趋于收敛，表明网络参数已达到最优。为避免过度训练带来的过拟合风险和计算成本，将迭代次数设置为120。
3. CSAE网络训练完成后，将其用于数据集B中火焰图像的特征提取，得到特征向量h3。尽管不同阶段下的原始火焰图像不能直观区分，但在特征空间上表现出良好的可分性。
4. 利用数据集B的火焰图像特征和标签对Soft-max分类器进行训练，以优化参数。通过数据集C进行CSAE-Soft-max模型的性能测试，检验该模型对燃烧阶段的识别能力，成功率高达98.9%。
5. 所建立的CSAE网络能够以无监督方式提取图像特征，并通过Soft-max分类器实现特征分类，从而识别单张火焰图像的燃烧工况，通过在300MW电站锅炉上采集的火焰图像，对所提CSAE-Soft-max模型的识别性能进行测试。
   结果表明，在不需要先验专家知识和缺乏标签数据的情况下，CSAE-Soft-max模型能够准确识别不同燃烧阶段，识别精度达到98.9%。
** 结论
1. 所提出的方法是利用大量无标签图像训练CSAE网络，利用少数标签图像训练Soft-max分类器，在一定程度上解决了网络训练存在的标签数据受限问题。
2. CSAE网络的重构误差较小时，所提取的图像特征能够代表原始火焰图像，为获得较高的识别精度提供了保证。
3. 相同阶段下的特征自动聚类，而不同阶段下的特征相互分离。
4. 虽然存在误分类现象，但绝大多数样本均被正确识别，成功率高达98.9%， 所提出模型能够高精度地识别不同燃烧阶段。
5. 该文章所提方法具有一定借鉴性，且数据集结构、实验过程及网络结构等描述清晰，应用点也较为接近，可更进一步仔细研读。
* 朱锡洲. 基于特征光流的视频中的物体检测[D]. 中国科学技术大学,2020.
** 问题
1. 通过算法从拍摄的图像或视频中检测出物体位置和类别，具有重要的研究意义和广泛的实际应用价值；
2. 现有的视频检测算法需要手工设计规则在检测速度和检测准确率方面面临着巨大的挑战。
** 方法
一种基于特征光流的视频物体检测框架，利用特征光流刻画邻近帧在特征层面发生的相对运动，并通过端到端的训练自动抽取所需特征层面时域信息，从而实现了快速、准确的视频中物体检测。
** 讨论
1. 针对特征层面的运动估计提出了特征光流：一个２维的向量场，刻画邻近帧之间在特征图上发生的相对运动。
2. 算法在稀疏关键帧上进行耗时的特征提取，并依据特征光流将关键帧的特征传播到其他帧。传播后特征图直接经由检测子网络输出检测结果。
3. ImageNet VID数据集用于视频物体检测任务，Cityscapes数据集用于城市街道场景理解和自动驾驶任务，用于视频语义分割任务。
4. 逐帧图像识别、SFF、所提出方法、所提出方法的几个变种，进行对比实验，比较准确率和速度；并讨论了在各种不同实验配置下的速度与准确率均衡，以及特征提取子网络和识别子网络不同划分下的识别准确率问题。
** 结论
1. 文章所提出方法能取得最佳的性能。它的准确率略低于逐帧图像识别基线，但运行速度上，在物体检测任务中加速5倍，在语义分割任务中加速3.7倍。
2. 所提出方法能取得显著的加速比，准确率有所下降，能比较平滑地调整速度与准确率之间的平衡。
3. 各种划分下的识别准确率差异很小、可忽略不计，识别子网络包含的运算越多，运行速度越慢。０层卷积和１层卷积时，运行速度与识别准确率基本一样。
4. 所提出算法对物体进行的检测类似于分类打标签，无法较好的运用到课题里。
* 作者. 题目. 期刊[J]. 年, 卷(期):页码.
** 问题（能够回答两个问题：最终要解决的大问题，本文要解决的特定问题）
** 方法（使用了什么方法，进行了哪些改进或是整合）
** 讨论（对实验结果进行了哪些讨论）
** 结论（注意是否解决了前面提出的特殊问题）

