* 王煜伟,田宏伟,秦永新,韩哲哲,许传龙.基于火焰图像和卷积稀疏自编码的燃烧工况监测[J].动力工程学报,2020,40(09):713-719.
** 问题
1. 不稳定燃烧不仅会降低能源利用效率，增加污染物排放量，还可能造成热分布不均匀、炉壁热应力增大等问题。因此，有必要对锅炉燃烧状态进行有效监测，以确保锅炉安全稳定运行。
2. 无监督学习网络在很大程度上降低了标签数据的需求量，自编码（AE）就是其中典型的无监督学习网络，但是AE在训练过程中往往会出现梯度消失或梯度爆炸等现象，且存在简单复制输入层信息的可能，不能真正获取图像的关键信息。因此，仍需开发更智能的图像特征提取方法。
** 方法
一种基于卷积稀疏自编码（CSAE）的燃煤电站锅炉燃烧状态识别方法。
首先，建立的CSAE以无监督方式提取图像特征，然后通过Soft-max分类器实现特征分类，从而识别单张火焰图像的燃烧工况，最后在300MW电站锅炉上获取火焰图像，对所建立模型进行了训练与性能测试。
** 讨论
1. 火焰图像经过预处理后（将所有火焰图像尺寸压缩至64*64，并进行归一化处理），划分为训练集（80%）和测试集（20%）。用于训练CSAE网络的数据集包含３２４０张火焰图像，定义为数据集A；用于训练Soft-max分类器的数据集包含360张火焰图像，定义为数据集B；用于测试CASE-Soft-max模型的数据集包含900张火焰图像，定义为数据集C。
2. 利用数据集A对CSAE网络进行训练。随着迭代次数的增加，重构误差进一步减小，并在120次迭代训练后趋于收敛，表明网络参数已达到最优。为避免过度训练带来的过拟合风险和计算成本，将迭代次数设置为120。
3. CSAE网络训练完成后，将其用于数据集B中火焰图像的特征提取，得到特征向量h3。尽管不同阶段下的原始火焰图像不能直观区分，但在特征空间上表现出良好的可分性。相同阶段下的特征自动聚类，而不同阶段下的特征相互分离。
4. 利用数据集B的火焰图像特征和标签对Soft-max分类器进行训练，以优化参数。通过数据集C进行CSAE-Soft-max模型的性能测试，检验该模型对燃烧阶段的识别能力，成功率高达98.9%。
5. 所建立的CSAE网络能够以无监督方式提取图像特征，并通过Soft-max分类器实现特征分类，从而识别单张火焰图像的燃烧工况，通过在300MW电站锅炉上采集的火焰图像，对所提CSAE-Soft-max模型的识别性能进行测试。
   结果表明，在不需要先验专家知识和缺乏标签数据的情况下，CSAE-Soft-max模型能够准确识别不同燃烧阶段，识别精度达到98.9%。
** 结论
该文章所提方法具有一定借鉴性，且实验过程及网络结果描述清晰，应用点也较为接近，可更进一步仔细研读。
* 朱锡洲. 基于特征光流的视频中的物体检测[D]. 中国科学技术大学,2020.
** 问题
1. 通过算法从拍摄的图像或视频中检测出物体位置和类别，具有重要的研究意义和广泛的实际应用价值；
2. 现有的视频检测算法需要手工设计规则在检测速度和检测准确率方面面临着巨大的挑战。
** 方法
一种基于特征光流的视频物体检测框架，利用特征光流刻画邻近帧在特征层面发生的相对运动，并通过端到端的训练自动抽取所需特征层面时域信息，从而实现了快速、准确的视频中物体检测。
** 讨论
1. 针对特征层面的运动估计提出了特征光流：一个２维的向量场，刻画邻近帧之间在特征图上发生的相对运动。
2. 算法在稀疏关键帧上进行耗时的特征提取，并依据特征光流将关键帧的特征传播到其他帧。传播后特征图直接经由检测子网络输出检测结果。
3. ImageNet VID数据集用于视频物体检测任务，Cityscapes数据集用于城市街道场景理解和自动驾驶任务，用于视频语义分割任务。
4. 逐帧图像识别、SFF、所提出方法、所提出方法的几个变种，进行对比实验，比较准确率和速度；并讨论了在各种不同实验配置下的速度与准确率均衡，以及特征提取子网络和识别子网络不同划分下的识别准确率问题。
** 结论
1. 文章所提出方法能取得最佳的性能。它的准确率略低于逐帧图像识别基线，但运行速度上，在物体检测任务中加速5倍，在语义分割任务中加速3.7倍。
2. 所提出方法能取得显著的加速比，准确率有所下降，能比较平滑地调整速度与准确率之间的平衡。
3. 各种划分下的识别准确率差异很小、可忽略不计，识别子网络包含的运算越多，运行速度越慢。０层卷积和１层卷积时，运行速度与识别准确率基本一样。
4. 所提出算法对物体进行的检测类似于分类打标签，无法较好的运用到课题里。
* 作者. 题目. 期刊[J]. 年, 卷(期):页码.
** 问题（能够回答两个问题：最终要解决的大问题，本文要解决的特定问题）
** 方法（使用了什么方法，进行了哪些改进或是整合）
** 讨论（对实验结果进行了哪些讨论）
** 结论（注意是否解决了前面提出的特殊问题）

